### ISSUE TITLE
what is networking did you use ?

### ISSUE THREAD

**Issue by stickylabdev** [GiotisK/Crystal-Battles-Unity-Android-Game#1]
interesting  ,,

**Comment by GiotisK** [comment]
> interesting ,,

I used Unity’s TransportLayer API. But I think its deprecated in Unity 2019. However you can check in Assets>Scripts and see my implementation of Networking

**Comment by stickylabdev** [comment]
may be you should use socketweaver :D

**Comment by GiotisK** [comment]
I think socketweaver is overkill for this small game 😆

**Comment by stickylabdev** [comment]
ouh ok ,, btw i tried your game , and i dont know where is the scene ,,, imean ,, i dont know how to play it ,,,,,,im looking for the scene but i cant find playable scene

**Comment by stickylabdev** [comment]
ouh ok ,, btw i tried your game , and i dont know where is the scene ,,,
imean ,, i dont know how to play it ,,,,,,im looking for the scene but i
cant find playable scene

Pada tanggal Sab, 14 Des 2019 pukul 01.27 Konstantinos Giotis <
notifications@github.com> menulis:

**Comment by GiotisK** [comment]
> ouh ok ,, btw i tried your game , and i dont know where is the scene ,,, imean ,, i dont know how to play it ,,,,,,im looking for the scene but i cant find playable scene

MainGameScene.unity should be the playable scene
